### ISSUE TITLE
[Feature Request] Batch Export for PyTILE

### ISSUE THREAD

**Issue by idmontie** [poiuyqwert/PyMS#1]
It would be nice to be able to select multiple groups of tiles and batch export them.  I believe TileEdit2 (which I can't even get to work) had that functionality.

If I have the time today, I'll try to fork your repo and implement the feature myself.

**Comment by poiuyqwert** [comment]
I don't plan on putting much working into the current PyTILE since I want to completely revamp the entire process since it has some major flaws in the way the import/export system works. For now you could write your own scripts to work with the tilesets. For example, here is a script (untested but should work) to export a few MegaTile Groups to BMP and TXT files:

    tileset_name = 'jungle'
    group_ids = (1,2,3)

    path = "/Users/zachzahos/Documents/Projects/PyMS/Libs/WORKING/tileset/"
    file_paths = [os.path.join(path,file_name % tileset_name) for file_name in ('%s.cv5','%s.vf4','%s.vx4','%s.vr4',os.path.join('%s','dddata.bin'),'%s.wpe')]
    print file_paths
    tileset = Tilesets.Tileset()
    tileset.load_file(*file_paths)
    for group_id in group_ids:
    	file_name = '%s-group-%d' % (tileset_name,group_id)
    	tileset.decompile(os.path.join(path,file_name + '.bmp'), id=group_id, settingfile=os.path.join(path,file_name + '.txt'))

**Comment by idmontie** [comment]
Thanks, I'll let you know if I get it to work later tonight :+1:
